helm/aragorn-ranker/.helmignore
helm/aragorn-ranker/Chart.yaml
helm/aragorn-ranker/Readme.md
helm/aragorn-ranker/templates/NOTES.txt
helm/aragorn-ranker/templates/_helpers.tpl
helm/aragorn-ranker/templates/deployment.yaml
helm/aragorn-ranker/templates/ingress.yaml
helm/aragorn-ranker/templates/service.yaml
helm/aragorn-ranker/values.yaml

Addition of helm config for aragorn-ranker

Addition of helm config for aragorn-ranker

---

helm/plater/templates/plater-deployment.yaml
helm/robokop/templates/cache-service.yaml
helm/robokop/templates/knowledge-graph-service.yaml
helm/robokop/templates/manager-service.yaml
helm/robokop/templates/omnicorp-postgres-service.yaml
helm/robokop/values.yaml

This pr updates Plater about.json mount
Adds loadbalancer config for robokop dbs

Plater update and Robokop loadbalancer config

---

helm/name-lookup/templates/solr-deployment.yaml

adding quiet mode to the solr command line.

adding solr quiet mode

---

helm/answer-coalesce/templates/service.yaml
helm/answer-coalesce/values.yaml

Ac service lb

---

helm/automat/templates/automat-deployment
helm/automat/templates/ingress.yaml
helm/automat/values.yaml
helm/plater/templates/configmap.yaml
helm/plater/templates/neo4j-deployment.yaml
helm/plater/templates/plater-deployment.yaml
helm/plater/values.yaml

Automat plater revamp

---

helm/aragorn/templates/deployment.yaml

this change adds the PVC for logging in the aragorn project.

adding the logging PVC

---

helm/aragorn-ranker/templates/NOTES.txt
helm/aragorn/templates/NOTES.txt
helm/filter_results_top_n/.helmignore
helm/filter_results_top_n/Chart.yaml
helm/filter_results_top_n/templates/NOTES.txt
helm/filter_results_top_n/templates/_helpers.tpl
helm/filter_results_top_n/templates/deployment.yaml
helm/filter_results_top_n/templates/ingress.yaml
helm/filter_results_top_n/templates/service.yaml
helm/filter_results_top_n/values.yaml

this one is for a site that Patrick created.
I have tested this and it is working as expected. as of this time the ingress is waiting to get worked out. values file can be found in the usual place.
also included in this were minor corrections to export command in the NOTES.txt files for aragorn and aragorn-ranker.
if satisfactory, you may merge and delete the branch.

install of Filter-results-top-n web app

---

helm/plater/templates/neo4j-deployment.yaml
helm/plater/templates/plater-deployment.yaml
helm/plater/values.yaml

gets the biolink model version from the helm chart's value file.

Bl variable update

---

helm/r3/templates/ingress.yaml
helm/strider/templates/ingress.yaml

increased strider timeout to 600s

Strider timeout

---

helm/plater/templates/configmap.yaml
helm/plater/templates/neo4j-deployment.yaml
helm/plater/values.yaml

- creates data dir's if they don't exists
- clears out data dir when seeding db

Neo4j 4.0 updates

---

helm/name-lookup/templates/ingress.yaml

this links to issue https://github.com/helxplatform/development/issues/708

for security we should not expose for public

---

helm/answer-coalesce/templates/redis-deployment.yaml
helm/answer-coalesce/templates/service.yaml
helm/answer-coalesce/values.yaml

some fixes for AC to bring it up to a stateful set deployment.

Ac deploy changes

---

helm/aragorn/templates/aragorn-logs-pvc.yaml
helm/aragorn/templates/deployment.yaml
helm/aragorn/values.yaml

adds pvc creation to aragorn chart

---

helm/chemical-normalization/Chart.yaml
helm/chemical-normalization/Readme.md
helm/chemical-normalization/templates/NOTES.txt
helm/chemical-normalization/templates/_helpers.tpl
helm/chemical-normalization/templates/configmap.yaml
helm/chemical-normalization/templates/ingress.yaml
helm/chemical-normalization/templates/redis-deployment.yaml
helm/chemical-normalization/templates/service.yaml
helm/chemical-normalization/templates/tests/test-connection.yaml
helm/chemical-normalization/templates/web-deployment.yaml
helm/chemical-normalization/values.yaml

r3 Chart has evolved so much that its no longer compatible with node norm chart 
this chart is a fix for that

Chem norm chart

---

helm/answer-coalesce/templates/redis-config-map.yaml
helm/answer-coalesce/values.yaml
helm/strider/values.yaml
helm/translator-workflow-runner/templates/deployment.yaml

minor modifications to add some parameters for some configuration items

Config changes

---

helm/strider/templates/hpa.yaml
helm/strider/templates/ingress.yaml
helm/strider/templates/service.yaml
helm/strider/templates/strider-deployment.yaml
helm/strider/values.yaml

values file is in the usual place.

implementing a new endpoint for strider (trapi 1.2)

---

helm/plater/templates/configmap.yaml
helm/plater/templates/plater-deployment.yaml
helm/plater/values.yaml

updated skip attbs , same as before, just rename of files.

Skip attributes

---

helm/aragorn-ranker/templates/deployment.yaml
helm/aragorn-ranker/values.yaml
helm/aragorn/templates/deployment.yaml
helm/aragorn/values.yaml

adding environment variables to control creating elapsed time in each of the aragorn module calls.

Debug timing

---

helm/answer-coalesce/ncats-images-meta.yaml
helm/api-watchdog/templates/cronjob.yaml
helm/api-watchdog/values.yaml
helm/aragorn-ranker/ncats-images-meta.yaml
helm/aragorn-ranker/templates/deployment.yaml
helm/aragorn-ranker/templates/env-config-map.yaml
helm/aragorn/ncats-images-meta.yaml
helm/aragorn/templates/env-config-map.yaml
helm/aragorn/values.yaml
helm/biolink-lookup/ncats-images-meta.yaml
helm/name-lookup/ncats-images-meta.yaml
helm/node-normalization-web-server/ncats-images-meta.yaml
helm/plater/ncats-images-meta.yaml
helm/plater/values.yaml

upping image version for name-res, installing env variables for api-watchdog

Upping image version

---

helm/aragorn/templates/env-config-map.yaml

removing unecessary NN URL env parm

---

helm/answer-coalesce/templates/ingress.yaml
helm/aragorn-ranker/templates/ingress.yaml
helm/aragorn/templates/ingress.yaml

there was a query that came back to aragorn from strider that exceeded max body size. this doubles the max length.

Increase max body sizes

---

monitoring/test-specs/aragorn.yaml
monitoring/test-specs/data/aragorn-data.csv

* name resolution addition, html email reporting
* name resolution addition, html email reporting
* name resolution addition, html email reporting
* runner fix jenkins volume issue using cp instead
* adding publish html
* automat + strider
* adding hmdb
* ontological hierarchy addition
* aragorn test

Feature/more monitoring (#163)

---

helm/aragorn/templates/aragorn-queue-files-pvc.yaml
helm/aragorn/templates/deployment.yaml
helm/aragorn/templates/rbtmq-persistence.yaml
helm/aragorn/values.yaml

creates and configures a PVC for saving async requests into a file.

Aragorn queue

---

helm/robokop/values.yaml

these have been verified to be ok after some final tweaks.

final tweaks for robokop cpu limits

---

helm/answer-coalesce/ncats-images-meta.yaml
helm/aragorn-ranker/ncats-images-meta.yaml
helm/aragorn/ncats-images-meta.yaml
helm/biolink-lookup/ncats-images-meta.yaml
helm/name-lookup/ncats-images-meta.yaml
helm/node-normalization-loader/ncats-images-meta.yaml
helm/node-normalization-web-server/ncats-images-meta.yaml

like the title says. a number of these did not have the latest version.

syncing up image version metadata with latest versions

---

helm/aragorn/templates/aragorn-logs-pvc.yaml
helm/aragorn/templates/aragorn-queue-files-pvc.yaml

* upping version
* removing duplicate entry
* changing the access modes to ReadWriteOnce

test sync (#286)

---

monitoring/Jenkinsfile

adding ssh file storing for tests

Monitoring ssh put

---

helm/name-lookup/templates/solr-deployment.yaml
helm/name-lookup/values.yaml
helm/omnicorp/templates/redis-statefulset.yaml
helm/omnicorp/templates/reload-postgres-job.yaml
helm/omnicorp/values.yaml
helm/plater/templates/neo4j-deployment.yaml
helm/plater/values.yaml
helm/r3/templates/redis-deployment.yaml
helm/r3/values.yaml
helm/robokop-ui-v2/templates/neo4j-statefulset.yaml
helm/robokop-ui-v2/values.yaml
helm/robokopkg/templates/neo4j-deployment.yaml
helm/robokopkg/values.yaml

adding init container explicit resource declarations

adding init container explicit resource declarations

---

helm/plater/values.yaml

bumps plater to new image with subclass fix.

plater version bump

---

helm/plater/values.yaml

Adding 1.3.0 to base value file.

Plater trapi bump

---

helm/cam-kp-api/templates/ingress.yaml

This is the same setup as used by e.g. Aragorn:
https://github.com/helxplatform/translator-devops/blob/7ec732e9de40c41cfab2d22887496b468c872a23/helm/aragorn/templates/ingress.yaml#L29-L34

Updated CAM-KP-API ingress as requested by NCATS.

---

helm/cam-kp-api/values.yaml
helm/translator-workflow-runner/ncats-images-meta.yaml

- bumps translator workflow runner

dev to test 

---

helm/toss/Chart.yaml
helm/toss/templates/NOTES.txt
helm/toss/templates/_helpers.tpl
helm/toss/templates/deployment.yaml
helm/toss/templates/ingress.yaml
helm/toss/templates/service.yaml
helm/toss/templates/tests/test-connection.yaml
helm/toss/values.yaml

Terms of service server is now running at https://toss.apps.renci.org/tos?service_long=Node+Normalization&provider_long=the+Translator+Consortium , 
next steps 
1. make public 
2. fix old links

terms of service server

---

helm/aragorn/ncats-images-meta.yaml
helm/strider/ncats-images-meta.yaml

Makes sure aragorn dev and strider dev are pushed to ci

bump image version

---

helm/plater/ncats-images-meta.yaml
helm/plater/values.yaml
helm/plater/values/sri-reference-kg/values-data.yaml

plater image bump and new monarch kg

---

helm/name-lookup/templates/restore-job.yaml
helm/name-lookup/templates/solr-deployment.yaml
helm/name-lookup/templates/tests/test-connection.yaml
helm/name-lookup/templates/web-deployment.yaml
helm/name-lookup/values.yaml

This PR adds nodeSelector/affinity/tolerations to name-lookup.

Add nodeSelector/affinity/tolerations to name-lookup

---

helm/plater/templates/deployment.yaml
helm/plater/templates/neo4j-deployment.yaml
helm/plater/values.yaml

adding node selector, tolerations, and affinity placeholders to plater

adding node selector, tolerations, and affinity placeholders to plater

---

helm/name-lookup/ncats-images-meta.yaml

Updated Name-Lookup ncats-images-meta to latest version

---

helm/information-radiator/values.yaml

Give the test harness more memory

Informationradiator

---

helm/cqs/ncats-images-meta.yaml

Adding truncated limits for each QueryTemplate & a hard limit of 250 Result instances for the merged Response.

incrementing version

---

helm/plater/templates/env-config-map.yaml

changing plater OTEL service names to include "automat-"

---

helm/plater/values.yaml

this works on Sterling so we'll try it on ITRB

adding http to host

---

helm/openapi-spec-aggregator/values.yaml

just adding a dev automat to the open api spec aggregator

adding ehr-may-treat-kp
