helxplatform/translator-devops

- helm/plater/templates/plater-deployment.yaml
- helm/plater/values.yaml
- Adds num_wokers and worker timeout
- when loading large graph such as robokopkg the first step of making predicates schema takes long time. Increasing the gunicorn timeout ensures that gunicorn doesn't kill the process before the operation finishes.
> Plater dep gunicorn config 

- helm/plater/templates/plater-deployment.yaml
- helm/plater/values.yaml
incorporating the provenance tag for trapi query graphs. 
associated values files are in the usual place and they have been updated to support provenance and the latest biolink model version..
> Provenance tag

- helm/plater/templates/neo4j-deployment.yaml
- helm/plater/values.yaml
Adds liveliness and ready ness probs to neo4j restarts will be triggered based on the number of failures specified
> adds liveliness and readiness probs to neo4j

- helm/node-normalization-web-server/templates/web-server-deployment.yaml
- helm/node-normalization-web-server/templates/web-server-service.yaml
avoids conflicting selectors when its deployed twice with different release name
> service selector for nn web server

- helm/plater/templates/configmap.yaml
- helm/plater/templates/plater-deployment.yaml
- helm/plater/values.yaml
bumps image version to latest build
adds skip attributes config to chart,
- provided_by : added on nodes by kgx
- knowledge_source: added on edges by kgx
both of these attributes contain the file names where the entities were residing
> plater adds skip attributes

- helm/node-normalization-loader/templates/data-pvc.yaml
- helm/node-normalization-loader/templates/loader-config.yaml
- helm/node-normalization-loader/templates/loader-job.yaml
- helm/node-normalization-loader/values.yaml
- helm/redis-r3-external/Chart.yaml
- helm/redis-r3-external/values.yaml
when loading using  a single job conflation is done for every compendia. This PR will split them into two jobs. The conflation job just loads the conflation files, likewise compendia job loads each compendia file.
- also update redis external chart , includes 2 mode dbs that had not been pushed to the repo
> Split loader as compendia and conflation jobs

- helm/plater/templates/neo4j-deployment.yaml
- helm/plater/values.yaml
- helm/strider/templates/strider-deployment.yaml
- helm/strider/values.yaml
- Adds node affinity and tolerations to enable selection of specific nodes to run neo4j on for plater. 
- Strider liveliness probe enable disable flag, and default period to 120s
> Plater strider updates

- helm/api-watchdog/templates/cronjob.yaml
draft pr for api-watchdog cronjob
I think I need to add 
- the name of the command `bash fetch-and-exec.sh`
- image (not uploaded yet)
> DRAFT: change target for cronjob

- helm/aragorn/templates/deployment.yaml
a securityConext has been added. this has to me mated with a container that specifies  the non-root user.
> adding security context to avoid the use of root in the pod

- helm/redis-r3-external/Chart.yaml
- helm/redis-r3-external/values.yaml
- this is some commits that i had previously missed to push
- it disables AOF, since AOF dumps are unnecessarily large for our use case it causes larger volume usage
- it adds enabled flag for Info-content redis deployment
> Disables AOF and add .enabled for redis chart

- helm/robokop/values.yaml
specifying cpu request/limits for those deploys that dont have them assigned. increasing cpu limits for backend and manager to avoid throttling.
> specifying cpu request/limits

- helm/node-normalization-web-server/templates/ingress.yaml
Adds ingress class attibuite for NN webserver. 
ITRB uses "nginx" ingress class, but it wasn't being reflected due to this missing lines.
> ingress class as attribute if version above 1.18

- monitoring/Jenkinsfile
- monitoring/run_test.sh
Since jenkins2.renci.org (blackbalsam) is moving to jenkins.apps.renci.org (Sterling), jobs can no longer rely on the docker socket if they want to run in Kubernets pods (preferred). Since these jobs don't rely on multiple containers, they didn't need the docker socket; the artillery container can be run directly by Jenkins via the k8s API.
Here's a successful build of this change: https://jenkins.apps.renci.org/job/Translator/job/Service%20health%20monitoring/job/Node%20normalization/job/node%20normalization%20(renci)%20DEV/4164/
> Remove reliance on docker socket for monitoring tests

- monitoring/Jenkinsfile
I'm getting frequent [Falco](https://falco.org/) alerts from these jobs about writing files below "/" or "/root". But strangely, I don't think the script actually does that. I suspect Falco is just getting confused somewhere.
Regardless, running as non-root is always a good idea :)
Tested here: https://jenkins.apps.renci.org/job/Translator/job/Service%20health%20monitoring/job/Name%20Resolution/job/Name%20resolution%20(renci)%20DEV/4189/console
> Run artillery pod as a non-root user

- helm/cam-kp-api/values.yaml
Turns out RENCI needs ingress.tls.enabled to be 'true', not 'false'. My bad!
> Fix bug in RENCI deployment in CAM-KP-API

- helm/node-normalization-web-server/templates/NOTES.txt
The Helm name is important because Aragorn accesses NodeNorm RENCI via its cluster name, so it's important that this remain unchanged. AFAIK there's no way of changing this from within the Helm chart (please correct me if I'm wrong!), so I've added it to the NOTES.txt file so it's displayed after deployments. A more long-term solution would be to have a NodeNorm user on Sterling (maybe Aragorn?) periodically check whether NodeNorm is up under a particular name, and to ping me or someone if that's not the case.
(Checking this from outside the cluster is covered by https://github.com/TranslatorSRI/NodeNormalization/issues/161, but we also need some way of checking this from inside the cluster.)
> We're changing the Helm name of NodeNorm from `nn-web-server` to `nn-web`

- helm/aragorn/values.yaml
bumps aragorn memory to 20Gi
- temporary fix till we get discussed changes
> bump aragorn memory

- helm/icees-api/values.yaml
This is for supporting the newly added multivariate analysis functionality in ICEES. With default nginx ingress timeout, the new endpoint would return a 504 gateway timeout response with a large input list of feature variables. Adding these timeout annotations resolved the gateway timeout response issue.
> Added nginx ingress timeout annotations

- helm/name-lookup/templates/scripts-config-map.yaml
- helm/name-lookup/values.yaml
We don't need to keep the downloaded Solr backup around. This PR modifies the download script to delete that file once it has been uncompressed.
In the future, it would be great if we could delete the uncompressed backup as well (/var/solr/data/var/solr/data/...), but this would need to happen after the restore.
> Decrease Name-Res storage to 300Gi by deleting the downloaded Solr backup

- helm/node-normalization-loader/ncats-images-meta.yaml
- helm/node-normalization-loader/templates/loader-pipe-job.yaml
- helm/node-normalization-web-server/ncats-images-meta.yaml
This PR fixes several issues in the NodeNorm loader that we discovered in trying to load this data into ITRB:
- `--tls` did not have proper spacing around it because of incorrect use of `{{-`.
- When using `redis-cli` with a Redis cluster, the `-c` flag is necessary to ensure that `MOVED` and `ASK` redirects are followed. This has now been added when the `is_cluster` flag is set.
- `BGSAVE` appears to be unnecessary on the cluster, and so this is removed when the `is_cluster` flag is set.
- We get a lot of `MOVED` messages from redis-cli, so we now filter them out with a crude grep to make it easier to spot actual errors.
- The version information in nn-loader's `ncats-images-meta.yaml` file should never be used, but for completeness I have updated it to the latest version.
> NodeNorm loader fixes

- helm/name-lookup/values.yaml
They were at the wrong indentation level. This PR fixes that.
> Fix affinity values for Name Lookup and NodeNorm

- helm/name-lookup/templates/restore-job.yaml
- helm/name-lookup/templates/scripts-config-map.yaml
- helm/name-lookup/values.yaml
NameLookup downloads a blocklist and deletes those concepts from the Solr database, but the blocklist is now large enough that it cannot be deleted in less than a second. This PR modifies the blocklist code so that it carries out deletions in chunks.
> Added code to chunk blocklist deletions in NameLookup

- helm/name-lookup/templates/web-deployment.yaml
- helm/name-lookup/values.yaml
NameLookup has been using the default resources for its web frontend. This PR allows resources to be explicitly configured for that node.
> Added support for explicitly setting app resources on NameLookup
